-- Migration: Replace All Product Types and Add Demo Products
-- This removes all existing types and creates 5 new types with 3 demo products each
-- Run this in Supabase SQL Editor
-- 
-- NOTE: SKUs will be auto-generated by database triggers if not provided
-- Make sure to run add_auto_sku_generation.sql first!

-- ============================================
-- 1. Remove All Existing Types and Relationships
-- ============================================

-- First, remove all product-type relationships from junction table
DELETE FROM product_types;

-- Remove type_id references from products (set to NULL)
UPDATE products SET type_id = NULL WHERE type_id IS NOT NULL;

-- Delete all existing types
DELETE FROM types;

-- ============================================
-- 2. Create New Product Types (5 Types)
-- ============================================

INSERT INTO types (name, slug, description, is_active, display_order) VALUES
  ('Chiffon saree', 'chiffon-saree', 'Elegant chiffon sarees with flowing drape', true, 1),
  ('Cotton saree', 'cotton-saree', 'Comfortable and breathable cotton sarees', true, 2),
  ('Designer saree', 'designer-saree', 'Exclusive designer sarees with unique patterns', true, 3),
  ('Japan satin saree', 'japan-satin-saree', 'Luxurious Japan satin sarees with smooth finish', true, 4),
  ('Ho silk saree', 'ho-silk-saree', 'Premium Ho silk sarees with rich texture', true, 5)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active,
  display_order = EXCLUDED.display_order;

-- ============================================
-- 3. Create Demo Products (3 products per type = 15 total)
-- ============================================

DO $$
DECLARE
  -- Type IDs
  v_chiffon_type_id UUID;
  v_cotton_type_id UUID;
  v_designer_type_id UUID;
  v_japan_satin_type_id UUID;
  v_ho_silk_type_id UUID;
  
  -- Product IDs
  v_product_id UUID;
  v_variant_id UUID;
  
  -- Counter
  i INT;
BEGIN
  -- Get type IDs
  SELECT id INTO v_chiffon_type_id FROM types WHERE slug = 'chiffon-saree' LIMIT 1;
  SELECT id INTO v_cotton_type_id FROM types WHERE slug = 'cotton-saree' LIMIT 1;
  SELECT id INTO v_designer_type_id FROM types WHERE slug = 'designer-saree' LIMIT 1;
  SELECT id INTO v_japan_satin_type_id FROM types WHERE slug = 'japan-satin-saree' LIMIT 1;
  SELECT id INTO v_ho_silk_type_id FROM types WHERE slug = 'ho-silk-saree' LIMIT 1;

  -- ============================================
  -- Chiffon Saree Products (3 products)
  -- ============================================
  
  -- Chiffon Saree 1: Red
  INSERT INTO products (
    name, slug, description, type_id, base_price, compare_at_price,
    sku, is_active, is_featured, color, display_order
  ) VALUES (
    'Elegant Red Chiffon Saree', 'elegant-red-chiffon-saree',
    'Beautiful red chiffon saree with elegant drape, perfect for parties and celebrations.',
    v_chiffon_type_id, 2999.00, 3999.00,
    'CHF-RED-001', true, true, 'Red', 1
  )
  ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    base_price = EXCLUDED.base_price,
    compare_at_price = EXCLUDED.compare_at_price,
    type_id = EXCLUDED.type_id,
    updated_at = NOW()
  RETURNING id INTO v_product_id;

  -- Link to type via junction table
  INSERT INTO product_types (product_id, type_id, display_order)
  VALUES (v_product_id, v_chiffon_type_id, 0)
  ON CONFLICT (product_id, type_id) DO NOTHING;

  -- Create variant with quantity 10
  INSERT INTO variants (
    product_id, name, sku, price, color, stock_quantity,
    track_inventory, is_active, display_order
  ) VALUES (
    v_product_id, 'Red Chiffon Saree', 'CHF-RED-001-V1',
    2999.00, 'Red', 10, true, true, 0
  )
  ON CONFLICT (sku) DO UPDATE SET
    stock_quantity = 10,
    price = EXCLUDED.price,
    updated_at = NOW();

  -- Chiffon Saree 2: Blue
  INSERT INTO products (
    name, slug, description, type_id, base_price, compare_at_price,
    sku, is_active, is_featured, color, display_order
  ) VALUES (
    'Royal Blue Chiffon Saree', 'royal-blue-chiffon-saree',
    'Stunning royal blue chiffon saree with graceful flow, ideal for evening events.',
    v_chiffon_type_id, 2999.00, 3999.00,
    'CHF-BLUE-002', true, false, 'Blue', 2
  )
  ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    base_price = EXCLUDED.base_price,
    compare_at_price = EXCLUDED.compare_at_price,
    type_id = EXCLUDED.type_id,
    updated_at = NOW()
  RETURNING id INTO v_product_id;

  INSERT INTO product_types (product_id, type_id, display_order)
  VALUES (v_product_id, v_chiffon_type_id, 0)
  ON CONFLICT (product_id, type_id) DO NOTHING;

  INSERT INTO variants (
    product_id, name, sku, price, color, stock_quantity,
    track_inventory, is_active, display_order
  ) VALUES (
    v_product_id, 'Royal Blue Chiffon Saree', 'CHF-BLUE-002-V1',
    2999.00, 'Blue', 10, true, true, 0
  )
  ON CONFLICT (sku) DO UPDATE SET
    stock_quantity = 10,
    price = EXCLUDED.price,
    updated_at = NOW();

  -- Chiffon Saree 3: Green
  INSERT INTO products (
    name, slug, description, type_id, base_price, compare_at_price,
    sku, is_active, is_featured, color, display_order
  ) VALUES (
    'Emerald Green Chiffon Saree', 'emerald-green-chiffon-saree',
    'Elegant emerald green chiffon saree with beautiful shimmer, perfect for special occasions.',
    v_chiffon_type_id, 2999.00, 3999.00,
    'CHF-GREEN-003', true, false, 'Green', 3
  )
  ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    base_price = EXCLUDED.base_price,
    compare_at_price = EXCLUDED.compare_at_price,
    type_id = EXCLUDED.type_id,
    updated_at = NOW()
  RETURNING id INTO v_product_id;

  INSERT INTO product_types (product_id, type_id, display_order)
  VALUES (v_product_id, v_chiffon_type_id, 0)
  ON CONFLICT (product_id, type_id) DO NOTHING;

  INSERT INTO variants (
    product_id, name, sku, price, color, stock_quantity,
    track_inventory, is_active, display_order
  ) VALUES (
    v_product_id, 'Emerald Green Chiffon Saree', 'CHF-GREEN-003-V1',
    2999.00, 'Green', 10, true, true, 0
  )
  ON CONFLICT (sku) DO UPDATE SET
    stock_quantity = 10,
    price = EXCLUDED.price,
    updated_at = NOW();

  -- ============================================
  -- Cotton Saree Products (3 products)
  -- ============================================
  
  -- Cotton Saree 1: Maroon
  INSERT INTO products (
    name, slug, description, type_id, base_price, compare_at_price,
    sku, is_active, is_featured, color, display_order
  ) VALUES (
    'Traditional Maroon Cotton Saree', 'traditional-maroon-cotton-saree',
    'Comfortable maroon cotton saree with traditional design, perfect for daily wear.',
    v_cotton_type_id, 1999.00, 2999.00,
    'COT-MAROON-001', true, true, 'Maroon', 1
  )
  ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    base_price = EXCLUDED.base_price,
    compare_at_price = EXCLUDED.compare_at_price,
    type_id = EXCLUDED.type_id,
    updated_at = NOW()
  RETURNING id INTO v_product_id;

  INSERT INTO product_types (product_id, type_id, display_order)
  VALUES (v_product_id, v_cotton_type_id, 0)
  ON CONFLICT (product_id, type_id) DO NOTHING;

  INSERT INTO variants (
    product_id, name, sku, price, color, stock_quantity,
    track_inventory, is_active, display_order
  ) VALUES (
    v_product_id, 'Traditional Maroon Cotton Saree', 'COT-MAROON-001-V1',
    1999.00, 'Maroon', 10, true, true, 0
  )
  ON CONFLICT (sku) DO UPDATE SET
    stock_quantity = 10,
    price = EXCLUDED.price,
    updated_at = NOW();

  -- Cotton Saree 2: Navy Blue
  INSERT INTO products (
    name, slug, description, type_id, base_price, compare_at_price,
    sku, is_active, is_featured, color, display_order
  ) VALUES (
    'Classic Navy Blue Cotton Saree', 'classic-navy-blue-cotton-saree',
    'Classic navy blue cotton saree with elegant border, ideal for office and formal wear.',
    v_cotton_type_id, 1999.00, 2999.00,
    'COT-NAVY-002', true, false, 'Navy Blue', 2
  )
  ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    base_price = EXCLUDED.base_price,
    compare_at_price = EXCLUDED.compare_at_price,
    type_id = EXCLUDED.type_id,
    updated_at = NOW()
  RETURNING id INTO v_product_id;

  INSERT INTO product_types (product_id, type_id, display_order)
  VALUES (v_product_id, v_cotton_type_id, 0)
  ON CONFLICT (product_id, type_id) DO NOTHING;

  INSERT INTO variants (
    product_id, name, sku, price, color, stock_quantity,
    track_inventory, is_active, display_order
  ) VALUES (
    v_product_id, 'Classic Navy Blue Cotton Saree', 'COT-NAVY-002-V1',
    1999.00, 'Navy Blue', 10, true, true, 0
  )
  ON CONFLICT (sku) DO UPDATE SET
    stock_quantity = 10,
    price = EXCLUDED.price,
    updated_at = NOW();

  -- Cotton Saree 3: Peach
  INSERT INTO products (
    name, slug, description, type_id, base_price, compare_at_price,
    sku, is_active, is_featured, color, display_order
  ) VALUES (
    'Soft Peach Cotton Saree', 'soft-peach-cotton-saree',
    'Soft peach cotton saree with delicate prints, comfortable for everyday use.',
    v_cotton_type_id, 1999.00, 2999.00,
    'COT-PEACH-003', true, false, 'Peach', 3
  )
  ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    base_price = EXCLUDED.base_price,
    compare_at_price = EXCLUDED.compare_at_price,
    type_id = EXCLUDED.type_id,
    updated_at = NOW()
  RETURNING id INTO v_product_id;

  INSERT INTO product_types (product_id, type_id, display_order)
  VALUES (v_product_id, v_cotton_type_id, 0)
  ON CONFLICT (product_id, type_id) DO NOTHING;

  INSERT INTO variants (
    product_id, name, sku, price, color, stock_quantity,
    track_inventory, is_active, display_order
  ) VALUES (
    v_product_id, 'Soft Peach Cotton Saree', 'COT-PEACH-003-V1',
    1999.00, 'Peach', 10, true, true, 0
  )
  ON CONFLICT (sku) DO UPDATE SET
    stock_quantity = 10,
    price = EXCLUDED.price,
    updated_at = NOW();

  -- ============================================
  -- Designer Saree Products (3 products)
  -- ============================================
  
  -- Designer Saree 1: Gold
  INSERT INTO products (
    name, slug, description, type_id, base_price, compare_at_price,
    sku, is_active, is_featured, color, display_order
  ) VALUES (
    'Luxurious Gold Designer Saree', 'luxurious-gold-designer-saree',
    'Exclusive gold designer saree with intricate embroidery and premium finish.',
    v_designer_type_id, 8999.00, 12999.00,
    'DSG-GOLD-001', true, true, 'Gold', 1
  )
  ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    base_price = EXCLUDED.base_price,
    compare_at_price = EXCLUDED.compare_at_price,
    type_id = EXCLUDED.type_id,
    updated_at = NOW()
  RETURNING id INTO v_product_id;

  INSERT INTO product_types (product_id, type_id, display_order)
  VALUES (v_product_id, v_designer_type_id, 0)
  ON CONFLICT (product_id, type_id) DO NOTHING;

  INSERT INTO variants (
    product_id, name, sku, price, color, stock_quantity,
    track_inventory, is_active, display_order
  ) VALUES (
    v_product_id, 'Luxurious Gold Designer Saree', 'DSG-GOLD-001-V1',
    8999.00, 'Gold', 10, true, true, 0
  )
  ON CONFLICT (sku) DO UPDATE SET
    stock_quantity = 10,
    price = EXCLUDED.price,
    updated_at = NOW();

  -- Designer Saree 2: Purple
  INSERT INTO products (
    name, slug, description, type_id, base_price, compare_at_price,
    sku, is_active, is_featured, color, display_order
  ) VALUES (
    'Royal Purple Designer Saree', 'royal-purple-designer-saree',
    'Stunning royal purple designer saree with contemporary design and premium quality.',
    v_designer_type_id, 8999.00, 12999.00,
    'DSG-PURPLE-002', true, false, 'Purple', 2
  )
  ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    base_price = EXCLUDED.base_price,
    compare_at_price = EXCLUDED.compare_at_price,
    type_id = EXCLUDED.type_id,
    updated_at = NOW()
  RETURNING id INTO v_product_id;

  INSERT INTO product_types (product_id, type_id, display_order)
  VALUES (v_product_id, v_designer_type_id, 0)
  ON CONFLICT (product_id, type_id) DO NOTHING;

  INSERT INTO variants (
    product_id, name, sku, price, color, stock_quantity,
    track_inventory, is_active, display_order
  ) VALUES (
    v_product_id, 'Royal Purple Designer Saree', 'DSG-PURPLE-002-V1',
    8999.00, 'Purple', 10, true, true, 0
  )
  ON CONFLICT (sku) DO UPDATE SET
    stock_quantity = 10,
    price = EXCLUDED.price,
    updated_at = NOW();

  -- Designer Saree 3: Pink
  INSERT INTO products (
    name, slug, description, type_id, base_price, compare_at_price,
    sku, is_active, is_featured, color, display_order
  ) VALUES (
    'Elegant Pink Designer Saree', 'elegant-pink-designer-saree',
    'Beautiful pink designer saree with modern patterns and elegant styling.',
    v_designer_type_id, 8999.00, 12999.00,
    'DSG-PINK-003', true, false, 'Pink', 3
  )
  ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    base_price = EXCLUDED.base_price,
    compare_at_price = EXCLUDED.compare_at_price,
    type_id = EXCLUDED.type_id,
    updated_at = NOW()
  RETURNING id INTO v_product_id;

  INSERT INTO product_types (product_id, type_id, display_order)
  VALUES (v_product_id, v_designer_type_id, 0)
  ON CONFLICT (product_id, type_id) DO NOTHING;

  INSERT INTO variants (
    product_id, name, sku, price, color, stock_quantity,
    track_inventory, is_active, display_order
  ) VALUES (
    v_product_id, 'Elegant Pink Designer Saree', 'DSG-PINK-003-V1',
    8999.00, 'Pink', 10, true, true, 0
  )
  ON CONFLICT (sku) DO UPDATE SET
    stock_quantity = 10,
    price = EXCLUDED.price,
    updated_at = NOW();

  -- ============================================
  -- Japan Satin Saree Products (3 products)
  -- ============================================
  
  -- Japan Satin Saree 1: Black
  INSERT INTO products (
    name, slug, description, type_id, base_price, compare_at_price,
    sku, is_active, is_featured, color, display_order
  ) VALUES (
    'Classic Black Japan Satin Saree', 'classic-black-japan-satin-saree',
    'Sophisticated black Japan satin saree with smooth finish and elegant drape.',
    v_japan_satin_type_id, 4999.00, 6999.00,
    'JPS-BLACK-001', true, true, 'Black', 1
  )
  ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    base_price = EXCLUDED.base_price,
    compare_at_price = EXCLUDED.compare_at_price,
    type_id = EXCLUDED.type_id,
    updated_at = NOW()
  RETURNING id INTO v_product_id;

  INSERT INTO product_types (product_id, type_id, display_order)
  VALUES (v_product_id, v_japan_satin_type_id, 0)
  ON CONFLICT (product_id, type_id) DO NOTHING;

  INSERT INTO variants (
    product_id, name, sku, price, color, stock_quantity,
    track_inventory, is_active, display_order
  ) VALUES (
    v_product_id, 'Classic Black Japan Satin Saree', 'JPS-BLACK-001-V1',
    4999.00, 'Black', 10, true, true, 0
  )
  ON CONFLICT (sku) DO UPDATE SET
    stock_quantity = 10,
    price = EXCLUDED.price,
    updated_at = NOW();

  -- Japan Satin Saree 2: White
  INSERT INTO products (
    name, slug, description, type_id, base_price, compare_at_price,
    sku, is_active, is_featured, color, display_order
  ) VALUES (
    'Pure White Japan Satin Saree', 'pure-white-japan-satin-saree',
    'Elegant white Japan satin saree with pristine finish, perfect for special occasions.',
    v_japan_satin_type_id, 4999.00, 6999.00,
    'JPS-WHITE-002', true, false, 'White', 2
  )
  ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    base_price = EXCLUDED.base_price,
    compare_at_price = EXCLUDED.compare_at_price,
    type_id = EXCLUDED.type_id,
    updated_at = NOW()
  RETURNING id INTO v_product_id;

  INSERT INTO product_types (product_id, type_id, display_order)
  VALUES (v_product_id, v_japan_satin_type_id, 0)
  ON CONFLICT (product_id, type_id) DO NOTHING;

  INSERT INTO variants (
    product_id, name, sku, price, color, stock_quantity,
    track_inventory, is_active, display_order
  ) VALUES (
    v_product_id, 'Pure White Japan Satin Saree', 'JPS-WHITE-002-V1',
    4999.00, 'White', 10, true, true, 0
  )
  ON CONFLICT (sku) DO UPDATE SET
    stock_quantity = 10,
    price = EXCLUDED.price,
    updated_at = NOW();

  -- Japan Satin Saree 3: Silver
  INSERT INTO products (
    name, slug, description, type_id, base_price, compare_at_price,
    sku, is_active, is_featured, color, display_order
  ) VALUES (
    'Shimmering Silver Japan Satin Saree', 'shimmering-silver-japan-satin-saree',
    'Gorgeous silver Japan satin saree with metallic sheen and luxurious feel.',
    v_japan_satin_type_id, 4999.00, 6999.00,
    'JPS-SILVER-003', true, false, 'Silver', 3
  )
  ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    base_price = EXCLUDED.base_price,
    compare_at_price = EXCLUDED.compare_at_price,
    type_id = EXCLUDED.type_id,
    updated_at = NOW()
  RETURNING id INTO v_product_id;

  INSERT INTO product_types (product_id, type_id, display_order)
  VALUES (v_product_id, v_japan_satin_type_id, 0)
  ON CONFLICT (product_id, type_id) DO NOTHING;

  INSERT INTO variants (
    product_id, name, sku, price, color, stock_quantity,
    track_inventory, is_active, display_order
  ) VALUES (
    v_product_id, 'Shimmering Silver Japan Satin Saree', 'JPS-SILVER-003-V1',
    4999.00, 'Silver', 10, true, true, 0
  )
  ON CONFLICT (sku) DO UPDATE SET
    stock_quantity = 10,
    price = EXCLUDED.price,
    updated_at = NOW();

  -- ============================================
  -- Ho Silk Saree Products (3 products)
  -- ============================================
  
  -- Ho Silk Saree 1: Orange
  INSERT INTO products (
    name, slug, description, type_id, base_price, compare_at_price,
    sku, is_active, is_featured, color, display_order
  ) VALUES (
    'Vibrant Orange Ho Silk Saree', 'vibrant-orange-ho-silk-saree',
    'Rich orange Ho silk saree with traditional motifs and premium quality.',
    v_ho_silk_type_id, 6999.00, 9999.00,
    'HOS-ORANGE-001', true, true, 'Orange', 1
  )
  ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    base_price = EXCLUDED.base_price,
    compare_at_price = EXCLUDED.compare_at_price,
    type_id = EXCLUDED.type_id,
    updated_at = NOW()
  RETURNING id INTO v_product_id;

  INSERT INTO product_types (product_id, type_id, display_order)
  VALUES (v_product_id, v_ho_silk_type_id, 0)
  ON CONFLICT (product_id, type_id) DO NOTHING;

  INSERT INTO variants (
    product_id, name, sku, price, color, stock_quantity,
    track_inventory, is_active, display_order
  ) VALUES (
    v_product_id, 'Vibrant Orange Ho Silk Saree', 'HOS-ORANGE-001-V1',
    6999.00, 'Orange', 10, true, true, 0
  )
  ON CONFLICT (sku) DO UPDATE SET
    stock_quantity = 10,
    price = EXCLUDED.price,
    updated_at = NOW();

  -- Ho Silk Saree 2: Teal
  INSERT INTO products (
    name, slug, description, type_id, base_price, compare_at_price,
    sku, is_active, is_featured, color, display_order
  ) VALUES (
    'Elegant Teal Ho Silk Saree', 'elegant-teal-ho-silk-saree',
    'Beautiful teal Ho silk saree with intricate work and luxurious texture.',
    v_ho_silk_type_id, 6999.00, 9999.00,
    'HOS-TEAL-002', true, false, 'Teal', 2
  )
  ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    base_price = EXCLUDED.base_price,
    compare_at_price = EXCLUDED.compare_at_price,
    type_id = EXCLUDED.type_id,
    updated_at = NOW()
  RETURNING id INTO v_product_id;

  INSERT INTO product_types (product_id, type_id, display_order)
  VALUES (v_product_id, v_ho_silk_type_id, 0)
  ON CONFLICT (product_id, type_id) DO NOTHING;

  INSERT INTO variants (
    product_id, name, sku, price, color, stock_quantity,
    track_inventory, is_active, display_order
  ) VALUES (
    v_product_id, 'Elegant Teal Ho Silk Saree', 'HOS-TEAL-002-V1',
    6999.00, 'Teal', 10, true, true, 0
  )
  ON CONFLICT (sku) DO UPDATE SET
    stock_quantity = 10,
    price = EXCLUDED.price,
    updated_at = NOW();

  -- Ho Silk Saree 3: Magenta
  INSERT INTO products (
    name, slug, description, type_id, base_price, compare_at_price,
    sku, is_active, is_featured, color, display_order
  ) VALUES (
    'Bold Magenta Ho Silk Saree', 'bold-magenta-ho-silk-saree',
    'Stunning magenta Ho silk saree with rich color and premium finish.',
    v_ho_silk_type_id, 6999.00, 9999.00,
    'HOS-MAGENTA-003', true, false, 'Magenta', 3
  )
  ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    base_price = EXCLUDED.base_price,
    compare_at_price = EXCLUDED.compare_at_price,
    type_id = EXCLUDED.type_id,
    updated_at = NOW()
  RETURNING id INTO v_product_id;

  INSERT INTO product_types (product_id, type_id, display_order)
  VALUES (v_product_id, v_ho_silk_type_id, 0)
  ON CONFLICT (product_id, type_id) DO NOTHING;

  INSERT INTO variants (
    product_id, name, sku, price, color, stock_quantity,
    track_inventory, is_active, display_order
  ) VALUES (
    v_product_id, 'Bold Magenta Ho Silk Saree', 'HOS-MAGENTA-003-V1',
    6999.00, 'Magenta', 10, true, true, 0
  )
  ON CONFLICT (sku) DO UPDATE SET
    stock_quantity = 10,
    price = EXCLUDED.price,
    updated_at = NOW();

  RAISE NOTICE 'Migration completed successfully!';
  RAISE NOTICE 'Created 5 types and 15 products (3 per type) with variants (quantity 10 each)';
END $$;





